#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

exec conky -c  ~/.config/conky/conky.conf &
exec feh --bg-fill -z Downloads/wallpapers &
exec setxkbmap pt &
exec /usr/libexec/polkit-gnome-authentication-agent-1 &
exec start-pulseaudio-x11 &
